@url = http://localhost:4100/api/problems
@id = d8fe17bf-119a-4698-9a31-ecdeaa6a367d

GET {{url}}

###
GET {{url}}/{{id}}

###
POST {{url}}
Content-Type: application/json

{
    "name": "Kolam Kebakaran",
    "description": "Panggl Bombe",
    "activityTemplateId": "f4b14845-fa81-4b3f-9eb8-0a7999854361"
}

###
PATCH {{url}}/{{id}}
Content-Type: application/json

{
    "name": "Lele 60 Hari"
}

###
DELETE {{url}}/{{id}}

###
GET {{url}}/get/f4b14845-fa81-4b3f-9eb8-0a7999854361